#!/usr/bin/env bash
set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'

if ! command -v fzf &>/dev/null
then
    echo "fzf could not be found, please install fzf"
    exit 1
fi

namespace=$(kubectl get ns --no-headers -o custom-columns=":metadata.name" | fzf)
echo "Namespace selected: $namespace"
podname=$(kubectl get pods -n "$namespace" --no-headers -o custom-columns=":metadata.name" --field-selector=status.phase=="Running" | fzf)
echo "Selected pod: $podname"
container=$(kubectl get pods -n "$namespace" "$podname" -o jsonpath='{.spec.containers[*].name}' | sed 's/ /\n/g' | fzf)
echo "Entering $podname,$container with sh"
kubectl exec -n "$namespace" --stdin --tty "$podname" -c "$container" -- /bin/sh
